name: Deploy Resume Website

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::262892772531:role/aws-terraform-github-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform_files
        run: terraform init

      - name: Read Terraform Outputs
        working-directory: terraform_files
        run: |
          echo "BUCKET_NAME=$(terraform output -raw bucket_name)" >> $GITHUB_ENV
          echo "DIST_ID=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_ENV

      - name: Deploy Website to S3
        run: |
          aws s3 sync website_code/ s3://$BUCKET_NAME --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $DIST_ID \
            --paths "/*"